import type { AwardTypeCode, ParsedCertificateCode } from '../types';
import { AWARD_TYPES } from './brand';

/** GYD-26-0001-01 → event / year / participant id / award type */
const CODE_PATTERN = /^([A-Z]{2,5})-(\d{2})-(\d{4})-(0[1-6])$/;

export const EVENT_CODES: Record<string, string> = {
  GYD: 'GurX Youth Design',
};

export function parseCertificateCode(input: string): ParsedCertificateCode {
  const raw = input.trim().toUpperCase();
  const match = CODE_PATTERN.exec(raw);

  if (!match) {
    return {
      raw,
      eventCode: '',
      year: 0,
      participantId: '',
      awardType: '01',
      valid: false,
    };
  }

  const [, eventCode, yy, participantId, awardType] = match;

  return {
    raw,
    eventCode,
    year: 2000 + Number(yy),
    participantId,
    awardType: awardType as AwardTypeCode,
    valid: true,
  };
}

export function buildCertificateCode(
  eventCode: string,
  year: number,
  participantNo: number,
  awardType: AwardTypeCode,
): string {
  const yy = String(year % 100).padStart(2, '0');
  const id = String(participantNo).padStart(4, '0');
  return `${eventCode}-${yy}-${id}-${awardType}`;
}

export function certificateVerifyUrl(code: string, origin?: string): string {
  const base = origin ?? (typeof window !== 'undefined' ? window.location.origin : '');
  return `${base}/certificate/verify/${code}`;
}

export function awardMetaFor(code: AwardTypeCode) {
  return AWARD_TYPES[code] ?? AWARD_TYPES['01'];
}

export function eventNameFor(eventCode: string): string {
  return EVENT_CODES[eventCode] ?? eventCode;
}

/**
 * QR image for the verification link. Generated by a public QR service so the
 * bundle stays dependency-free; swap for a local generator if offline QR is needed.
 */
export function qrImageUrl(value: string, size = 220): string {
  return `https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&margin=0&data=${encodeURIComponent(value)}`;
}
